image:
  file: docker/gitpod/Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - vscjava.vscode-java-pack
    - github.vscode-pull-request-github
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
    - hbenl.vscode-test-explorer
    - vscjava.vscode-java-dependency
    - redhat.fabric8-analytics
    - vscjava.vscode-java-debug

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
