#--------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
#
# This file contains a custom docker configuration that Gitpod will use for the underlying image for the Gitpod 
# borwser IDE.
#
# For useful context regarding custom Dockerfiles and images for GitPod see these links:
# https://www.gitpod.io/docs/config-docker
# https://www.gitpod.io/blog/docker-in-gitpod
#
#--------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
FROM gitpod/workspace-full