name: junit5 tests
on:
  push:
  schedule:
    - cron:  '0 3 * * *'
jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        java: ['11', '17']
    name: JUnit action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}${{ matrix.java }}${{ matrix.os }}
          restore-keys: ${{ runner.os }}-m2
